#!/bin/bash

export ROS_PACKAGE_PATH=~/Desktop/me537/coffeemachine/ros_tests/ros_rviz_ode_basic_working:/opt/ros/cturtle/stacks

rosmake diff_drive_simulation

rosrun diff_drive_simulation simulation #&

#rosrun rviz rviz -t /my_frame -f /my_frame
